/**
 * Shabab360 Export Utilities
 * Supports Excel (.xlsx), CSV, and browser print-to-PDF export.
 */

import ExcelJS from "exceljs";
import { saveAs } from "file-saver";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface ExportColumn {
  key: string;
  header: string;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/** Flatten a nested object one level deep (e.g. { city: { name: "X" } } → { "city.name": "X" }) */
function flattenRow(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(row)) {
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      for (const [ck, cv] of Object.entries(v as Record<string, unknown>)) {
        out[`${k}.${ck}`] = cv;
      }
    } else {
      out[k] = v;
    }
  }
  return out;
}

/** Format a date-like value in PKT timezone for Excel display */
function formatCellDate(value: unknown): string {
  if (!value) return "";
  if (typeof value === "string") {
    // If it looks like an ISO date, format it
    if (/^\d{4}-\d{2}-\d{2}/.test(value)) {
      try {
        const d = new Date(value);
        return d.toLocaleDateString("en-PK", {
          timeZone: "Asia/Karachi",
          year: "numeric",
          month: "short",
          day: "2-digit",
        });
      } catch {
        return value;
      }
    }
  }
  if (value instanceof Date) {
    return value.toLocaleDateString("en-PK", {
      timeZone: "Asia/Karachi",
      year: "numeric",
      month: "short",
      day: "2-digit",
    });
  }
  return String(value ?? "");
}

/* ------------------------------------------------------------------ */
/*  Excel Export                                                       */
/* ------------------------------------------------------------------ */

export async function exportToExcel<T extends Record<string, unknown>>(
  data: T[],
  filename: string,
  columns: ExportColumn[]
): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Data", {
    views: [{ showGridLines: false }],
  });

  // Brand colors
  const HEADER_FILL = {
    type: "pattern" as const,
    pattern: "solid" as const,
    fgColor: { argb: "FF4B0A8F" },
  };
  const HEADER_FONT: Partial<ExcelJS.Font> = {
    bold: true,
    color: { argb: "FFFFFFFF" },
    size: 11,
    name: "Segoe UI",
  };
  const BORDER_STYLE: Partial<ExcelJS.Borders> = {
    bottom: { style: "thin", color: { argb: "FFDED6E3" } },
    right: { style: "thin", color: { argb: "FFDED6E3" } },
  };

  // Header row
  const headerRow = sheet.addRow(columns.map((c) => c.header));
  headerRow.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = BORDER_STYLE;
    cell.padding = { top: 4, bottom: 4, left: 8, right: 8 };
  });
  headerRow.height = 28;

  // Data rows
  for (const item of data) {
    const flat = flattenRow(item as Record<string, unknown>);
    const row = sheet.addRow(
      columns.map((col) => {
        const val = flat[col.key];
        // Auto-format dates
        if (typeof val === "string" && /^\d{4}-\d{2}-\d{2}/.test(val)) {
          return formatCellDate(val);
        }
        return val ?? "";
      })
    );

    row.eachCell((cell, colNumber) => {
      cell.font = { size: 10, name: "Segoe UI" };
      cell.alignment = { vertical: "middle", horizontal: "left" };
      cell.border = BORDER_STYLE;
      cell.padding = { top: 3, bottom: 3, left: 8, right: 8 };

      // Alternate row shading
      if (row.number % 2 === 0) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF3ECF6" },
        };
      }
    });
  }

  // Auto-size columns (max 40 chars)
  sheet.columns.forEach((column, i) => {
    const col = columns[i];
    let maxLength = col.header.length;
    for (const item of data) {
      const flat = flattenRow(item as Record<string, unknown>);
      const val = String(flat[col.key] ?? "");
      maxLength = Math.max(maxLength, val.length);
    }
    column.width = Math.min(Math.max(maxLength + 3, 12), 40);
  });

  // Freeze header row
  sheet.views = [{ state: "frozen", ySplit: 1 }];

  // Add a small footer row with timestamp
  const footerRow = sheet.addRow([
    `Generated by Shabab360 on ${new Date().toLocaleDateString("en-PK", {
      timeZone: "Asia/Karachi",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })}`,
  ]);
  footerRow.getCell(1).font = {
    italic: true,
    size: 9,
    color: { argb: "FF6B5A7A" },
    name: "Segoe UI",
  };

  // Write buffer and save
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  saveAs(blob, `${filename}.xlsx`);
}

/* ------------------------------------------------------------------ */
/*  CSV Export                                                         */
/* ------------------------------------------------------------------ */

export function exportToCSV<T extends Record<string, unknown>>(
  data: T[],
  filename: string,
  columns: ExportColumn[]
): void {
  if (data.length === 0) return;

  const escapeCSV = (val: unknown): string => {
    const str = String(val ?? "");
    if (str.includes(",") || str.includes('"') || str.includes("\n")) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const headerLine = columns.map((c) => escapeCSV(c.header)).join(",");
  const rows = data.map((item) => {
    const flat = flattenRow(item as Record<string, unknown>);
    return columns.map((col) => escapeCSV(flat[col.key])).join(",");
  });

  const csv = [headerLine, ...rows].join("\n");
  const BOM = "\uFEFF"; // UTF-8 BOM for Excel compatibility
  const blob = new Blob([BOM + csv], { type: "text/csv;charset=utf-8;" });
  saveAs(blob, `${filename}.csv`);
}

/* ------------------------------------------------------------------ */
/*  PDF Export (Browser Print)                                         */
/* ------------------------------------------------------------------ */

export function exportToPDF(elementId: string, filename?: string): void {
  const element = document.getElementById(elementId);
  if (!element) {
    console.warn(`[export] Element #${elementId} not found.`);
    return;
  }

  // Add a temporary class for print targeting
  element.classList.add("print-target");

  // Store original title
  const originalTitle = document.title;
  if (filename) {
    document.title = filename;
  }

  window.print();

  // Restore
  document.title = originalTitle;
  element.classList.remove("print-target");
}