"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useSession } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Award, GraduationCap, Eye, ShieldCheck, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { ModuleFrame, ModuleMetric, ModuleSearch, ModuleEmpty, WorkflowNotice, moduleCard } from "@/components/modules/shared/module-presentation";
import { useEffectiveCapabilities } from "@/hooks/use-effective-capabilities";
async function read(url: string) { const r = await fetch(url, { cache: "no-store" }); if (!r.ok) throw new Error("Certificate preview could not be loaded"); return r.json(); }
export function CertificatesPage({ mobile = false, onBack }: { mobile?: boolean; onBack?: () => void } = {}) {
  const { data: session } = useSession(); const access = useEffectiveCapabilities();
  const [selected, setSelected] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const people = useQuery<{ data: { id: string; name: string }[]; pagination: { totalPages: number } }>({ queryKey: ["certificate-people", session?.user?.id, search, page], queryFn: () => read('/api/admin/students?' + new URLSearchParams({ search, page: String(page), pageSize: "20" })), enabled: access.has("reports.view") && access.has("students.profile.view") });
  const preview = useQuery({ queryKey: ["certificate-preview", session?.user?.id, selected], queryFn: () => read('/api/admin/certificates/' + selected), enabled: Boolean(selected && access.has("reports.view")) });
  return <ModuleFrame mobile={mobile} onBack={onBack} title="Certificates" subtitle="Participant achievement & certificate desk" actions={<span className="text-[10px] font-bold rounded-full px-3 py-1.5 bg-amber-50 text-amber-700 border border-amber-200">Preview only</span>}>
    <div className="grid grid-cols-3 gap-2"><ModuleMetric label="Participants" value={people.data?.data.length ?? "—"} detail="On this page" icon={GraduationCap} /><ModuleMetric label="Preview" value={preview.data ? "Ready" : "—"} icon={Eye} tone="emerald" /><ModuleMetric label="Issuance" value="Unavailable" icon={ShieldCheck} tone="amber" /></div>
    <WorkflowNotice>Preview participant details from current records. Certificate issuance, verification numbers, and sharing are currently unavailable.</WorkflowNotice>
    {access.isLoading ? <ModuleEmpty title="Loading permissions…" /> : !access.has("reports.view") ? <ModuleEmpty title="Certificate access is unavailable." icon={Award} /> : <>
      <div className={cn(moduleCard, "p-4")}><ModuleSearch label="Search participants" placeholder="Search participants…" value={search} onChange={value => { setSearch(value); setPage(1); }} /></div>
      {people.isError ? <p role="alert">The participant list could not be loaded. <button onClick={() => people.refetch()}>Retry</button></p> : people.isLoading ? <ModuleEmpty title="Loading participants…" /> : !people.data?.data.length ? <ModuleEmpty title="No matching participants." icon={GraduationCap} /> : <div className="grid gap-3 md:grid-cols-2">{people.data.data.map(p => <button key={p.id} onClick={() => setSelected(p.id)} className={cn(moduleCard, "p-4 flex gap-3 items-center text-left transition-colors hover:border-purple-300", selected === p.id && "ring-2 ring-purple-300")}><span className="size-11 rounded-2xl bg-purple-50 dark:bg-white/5 text-[#4B0A8F] dark:text-purple-300 flex items-center justify-center shrink-0"><Award className="size-6" /></span><span className="flex-1 min-w-0"><strong className="block text-sm">{p.name}</strong><span className="block text-[11px] text-slate-500 mt-1">View certificate preview</span></span><ChevronRight className="size-4 text-slate-400 shrink-0" /></button>)}</div>}
      <div className="flex justify-between items-center text-xs"><Button variant="ghost" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</Button><span>Page {page}</span><Button variant="ghost" disabled={page >= (people.data?.pagination.totalPages ?? 1)} onClick={() => setPage(p => p + 1)}>Next</Button></div>
      {selected && (preview.isLoading ? <ModuleEmpty title="Loading preview…" /> : preview.isError ? <p role="alert">Preview could not be loaded. <button onClick={() => preview.refetch()}>Retry</button></p> : preview.data && <article className="rounded-2xl bg-white dark:bg-[#180E30] shadow-md p-3"><div className="border-4 border-double border-purple-200 dark:border-purple-800 rounded-xl p-6 text-center space-y-4"><Award className="size-12 text-amber-500 mx-auto" /><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#4B0A8F] dark:text-purple-300">Shabab Alburhan</p><h2 className="font-black text-xl text-[#1F0860] dark:text-purple-200">Certificate preview</h2><span className="inline-block text-xs rounded-full bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-300 px-3 py-1">Draft — not issued</span><p className="text-2xl font-bold border-b border-purple-100 dark:border-white/10 pb-4">{preview.data.participant}</p><p className="text-sm">{preview.data.group} · {preview.data.batch}</p><p className="text-xs text-muted-foreground">{preview.data.park} · {preview.data.city}</p><div className="bg-purple-50/60 dark:bg-white/5 rounded-xl p-4 space-y-2"><p className="font-bold text-sm">Attendance: {preview.data.attendanceRate}%</p><p className="text-xs text-muted-foreground">Across {preview.data.totalEvents} eligible sessions</p><p className="text-xs text-muted-foreground">Batch end date: {preview.data.batchEndDate ?? "Not recorded"}</p></div></div></article>)}
    </>}
  </ModuleFrame>;
}
