"use client";
import { ReportsPage } from "./reports-page";
import { useState } from "react";
import { BarChart2, Users, CalendarCheck, Wallet, Package, Bookmark, Send, FileDown, Columns3, Filter, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ModuleFrame, ModuleMetric, ModuleTabs, ModuleEmpty, WorkflowNotice, moduleCard, moduleInput, moduleAction } from "@/components/modules/shared/module-presentation";
const domains = [{ id: "attendance", label: "Attendance", icon: CalendarCheck, columns: ["Participant", "Group", "Session date", "Attendance status"] }, { id: "admissions", label: "Admissions", icon: Users, columns: ["Applicant", "Application date", "Status", "Park"] }, { id: "finance", label: "Finance", icon: Wallet, columns: ["Fee event", "Participant", "Amount", "Receipt"] }, { id: "inventory", label: "Inventory", icon: Package, columns: ["Item", "Park", "Quantity", "Minimum stock"] }];
export function CustomReportBuilderPage({ mobile = false, onBack }: { mobile?: boolean; onBack?: () => void } = {}) {
  const [tab, setTab] = useState("builder"); const [domainId, setDomainId] = useState("attendance"); const [columns, setColumns] = useState<string[]>([]);
  const domain = domains.find(d => d.id === domainId)!;
  return <ModuleFrame mobile={mobile} onBack={onBack} title={mobile ? "Report Builder" : "Advanced Analytics & Custom Report Builder"} subtitle="Report fields, filters, presets & scheduled digests">
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ModuleMetric label="Saved presets" value="—" icon={Bookmark} /><ModuleMetric label="Scheduled digests" value="—" icon={Send} tone="emerald" />{!mobile && <><ModuleMetric label="Exports" value="—" icon={FileDown} tone="amber" /><ModuleMetric label="Domains" value={domains.length} detail="Report design categories" icon={BarChart2} /></>}</div>
    <WorkflowNotice>Custom columns, saved presets, and scheduled report delivery are currently unavailable. Use Standard reports for supported reports and exports. Builder selections are not saved.</WorkflowNotice>
    <ModuleTabs tabs={[{ id: "builder", label: "Custom builder" }, { id: "standard", label: "Standard reports" }, { id: "presets", label: "Saved presets" }, { id: "scheduled", label: "Scheduled digests" }]} value={tab} onChange={setTab} />
    {tab === "standard" ? <div className={cn(moduleCard, "p-3 sm:p-5 min-w-0 overflow-hidden")}><ReportsPage /></div> : tab === "presets" ? <ModuleEmpty title="Saved presets are unavailable" icon={Bookmark}>Saved report definitions will appear here when persistence is enabled.</ModuleEmpty> : tab === "scheduled" ? <ModuleEmpty title="Scheduled report delivery is unavailable" icon={Send}>No digest schedules or delivery acknowledgements are available.</ModuleEmpty> : <>
      <div className="flex gap-2 overflow-x-auto no-scrollbar">{domains.map(({ id, label, icon: Icon }) => <button key={id} aria-pressed={domainId === id} onClick={() => { setDomainId(id); setColumns([]); }} className={cn("rounded-xl px-3 py-2 text-xs font-bold flex gap-2 items-center whitespace-nowrap", domainId === id ? moduleAction : moduleCard)}><Icon className="size-4" />{label}</button>)}</div>
      <div className={cn("grid gap-4", !mobile && "lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]")}><div className="space-y-4"><div className={cn(moduleCard, "p-5 space-y-4")}><div className="flex justify-between gap-3"><h2 className="font-bold text-sm flex gap-2 items-center"><Columns3 className="size-4 text-purple-500" />Select export fields</h2><span className="text-xs text-purple-600">{columns.length} selected</span></div><div className="grid grid-cols-2 gap-3">{domain.columns.map(column => <label key={column} className="rounded-xl border border-slate-200 dark:border-white/10 p-3 text-xs flex gap-2 items-center"><input type="checkbox" checked={columns.includes(column)} onChange={e => setColumns(values => e.target.checked ? [...values, column] : values.filter(value => value !== column))} />{column}</label>)}</div></div><fieldset disabled className={cn(moduleCard, "p-5 space-y-4")}><h2 className="font-bold text-sm flex gap-2 items-center"><Filter className="size-4 text-purple-500" />Scope & date filters</h2><div className="grid grid-cols-2 gap-3">{["City", "Park", "Batch", "Date range"].map(label => <label key={label} className="text-xs font-bold space-y-2">{label}<select aria-label={label + " report filter"} className={moduleInput}><option>Unavailable</option></select></label>)}</div></fieldset></div><aside className={cn(moduleCard, "p-5 space-y-4 self-start")}><h2 className="font-bold text-sm flex gap-2 items-center"><Eye className="size-4 text-purple-500" />Report preview</h2><div className="rounded-xl border border-dashed border-purple-200 dark:border-purple-900 bg-purple-50/40 dark:bg-white/5 px-4 py-8 text-center"><BarChart2 className="size-8 text-purple-300 mx-auto mb-3" /><p className="text-xs text-muted-foreground">Custom report execution is unavailable.</p></div><Button disabled className={cn(moduleAction, "w-full rounded-xl gap-2")}><FileDown className="size-4" />Export report</Button><Button disabled variant="outline" className="w-full rounded-xl gap-2"><Bookmark className="size-4" />Save preset</Button></aside></div>
    </>}
  </ModuleFrame>;
}
