"use client";
import { useState } from "react";
import { Heart, BookOpen, Flame, Moon, Sun, Save, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ModuleFrame, ModuleMetric, ModuleTabs, ModuleEmpty, WorkflowNotice, moduleCard, moduleAction } from "@/components/modules/shared/module-presentation";
export function IslahMamulatPage({ onBack }: { onBack?: () => void } = {}) {
 const [tab, setTab] = useState("daily");
 return <ModuleFrame mobile onBack={onBack} title="Islah-i-Mamulat" subtitle="Spiritual routine, prayers & daily reflection">
   <WorkflowNotice>Daily logs and guidance are currently unavailable. Entries cannot be recorded or shared from this screen.</WorkflowNotice>
   <ModuleTabs tabs={[{ id: "daily", label: "My daily log" }, { id: "routine", label: "Routine" }, { id: "guidance", label: "Guidance" }]} value={tab} onChange={setTab} />
   <div className="grid grid-cols-3 gap-2"><ModuleMetric label="Daily progress" value="—" icon={Heart} tone="emerald" /><ModuleMetric label="Streak" value="—" icon={Flame} tone="amber" /><ModuleMetric label="Reading" value="—" icon={BookOpen} /></div>
   {tab === "daily" ? <fieldset disabled className="space-y-4"><div className={cn(moduleCard, "p-4 space-y-4")}><h2 className="font-bold text-sm flex gap-2 items-center"><Sun className="size-4 text-amber-500" />Daily prayer checklist</h2><div className="grid grid-cols-5 gap-2">{["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"].map(prayer => <label key={prayer} className="rounded-xl bg-emerald-50 dark:bg-emerald-950/20 p-2 text-center space-y-2"><span className="block text-[10px] font-bold text-emerald-800 dark:text-emerald-300">{prayer}</span><input type="checkbox" aria-label={prayer} /></label>)}</div></div><div className={cn(moduleCard, "p-4 space-y-3")}><h2 className="font-bold text-sm flex gap-2 items-center"><BookOpen className="size-4 text-purple-500" />Tilawat & daily habits</h2>{["Quran reading", "Morning azkar", "Evening azkar", "Mutalaah"].map(label => <label key={label} className="flex justify-between items-center text-xs border-b border-slate-100 dark:border-white/10 pb-3"><span>{label}</span><input type="checkbox" aria-label={label} /></label>)}<label className="block text-xs font-bold">Daily reflection<textarea aria-label="Daily reflection" className="block mt-2 w-full min-h-20 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 p-3" placeholder="Logging is currently unavailable" /></label></div><Button disabled className={cn(moduleAction, "w-full h-11 gap-2")}><Save className="size-4" />Save daily log — unavailable</Button></fieldset> : tab === "routine" ? <div className="space-y-3">{[{ title: "Morning routine", icon: Sun }, { title: "Evening routine", icon: Moon }, { title: "Reading & reflection", icon: BookOpen }].map(({ title, icon: Icon }) => <div key={title} className={cn(moduleCard, "p-5 flex gap-3 items-center")}><span className="p-3 rounded-xl bg-purple-50 dark:bg-white/5 text-purple-600"><Icon className="size-5" /></span><div><h2 className="text-sm font-bold">{title}</h2><p className="text-xs text-muted-foreground mt-1">Routine tracking is unavailable.</p></div></div>)}</div> : <ModuleEmpty title="Guidance is unavailable" icon={ShieldCheck}>Private guidance and log review will be available when the workflow is enabled.</ModuleEmpty>}
 </ModuleFrame>;
}
