"use client";
import { useState } from "react";
import { useSession } from "next-auth/react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffectiveCapabilities } from "@/hooks/use-effective-capabilities";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Package, AlertTriangle, ShoppingBag, Truck, Plus, MapPin } from "lucide-react";
import { cn } from "@/lib/utils";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { ModuleFrame, ModuleMetric, ModuleEmpty, ModuleSearch, ModuleTabs, WorkflowNotice, moduleCard, moduleInput, moduleAction } from "@/components/modules/shared/module-presentation";
import { toast } from "sonner";
type Stock = { id: string; parkId: string; itemId: string; quantity: number; minThreshold: number; park: { name: string }; item: { name: string; unit: string } };
type StockRequest = { id: string; quantity: number; reason: string; status: string; park: { name: string }; item: { name: string } };
type Order = { id: string; poNumber: string; quantity: number; status: string; supplierName: string; item: { name: string } };
async function read<T>(path: string): Promise<T> { const response = await fetch(path, { cache: "no-store" }); if (!response.ok) throw new Error("Procurement records could not be loaded"); return response.json(); }
export function ProcurementPage({ mobile = false, onBack }: { mobile?: boolean; onBack?: () => void } = {}) {
  const { data: session } = useSession(); return <ProcurementWorkspace key={session?.user?.id ?? "signed-out"} mobile={mobile} onBack={onBack} />;
}
function ProcurementWorkspace({ mobile, onBack }: { mobile: boolean; onBack?: () => void }) {
  const [tab, setTab] = useState("stock"); const [requestOpen, setRequestOpen] = useState(false); const [lowOnly, setLowOnly] = useState(false);
  const { data: session } = useSession(); const access = useEffectiveCapabilities(); const client = useQueryClient();
  const owner = session?.user?.id; const canView = access.has("organisation.view"); const canManage = access.has("organisation.manage");
  const [stockId, setStockId] = useState(""); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const stocks = useQuery({ queryKey: ["procurement-stock", owner], queryFn: () => read<Stock[]>("/api/admin/procurement/stock"), enabled: canView });
  const requests = useQuery({ queryKey: ["procurement-requests", owner], queryFn: () => read<StockRequest[]>("/api/admin/procurement/requests"), enabled: canView });
  const orders = useQuery({ queryKey: ["procurement-orders", owner], queryFn: () => read<Order[]>("/api/admin/procurement/orders"), enabled: canView });
  const mutation = useMutation({ mutationFn: async (operation: { path: string; method: string; body: unknown }) => {
    const response = await fetch(operation.path, { method: operation.method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(operation.body) });
    const data = await response.json().catch(() => null);
    if (!response.ok) throw new Error(typeof data?.error === "string" ? data.error : "Request was not acknowledged. Refresh records before retrying.");
    if (!data?.id) throw new Error("Request acknowledgement was incomplete. Refresh records before retrying."); return data;
  }, onSuccess: () => { toast.success("Saved to procurement records"); setRequestOpen(false); setQuantity(""); setReason(""); client.invalidateQueries({ queryKey: ["procurement-requests"] }); }, onError: (error: Error) => toast.error(error.message) });
  const filtered = (stocks.data ?? []).filter(stock => (stock.item.name + " " + stock.park.name).toLowerCase().includes(search.toLowerCase()) && (!lowOnly || stock.quantity < stock.minThreshold));
  const selected = stocks.data?.find(stock => stock.id === stockId);
  return <ModuleFrame mobile={mobile} gradient={mobile} onBack={onBack} title={mobile ? "اسٹاک و سامان" : "Procurement & Park Stock Inventory Desk"} subtitle="Park equipment, stock requests & purchase orders" actions={canManage ? <Button aria-label="Request stock refill" className={cn(moduleAction, "gap-1 text-xs")} onClick={() => setRequestOpen(true)}><Plus className="size-4" /><span className="hidden sm:inline">Request stock refill</span></Button> : undefined}>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ModuleMetric label="Inventory items" value={stocks.data?.length ?? "—"} icon={Package} /><ModuleMetric label="Low stock" value={stocks.data?.filter(s => s.quantity < s.minThreshold).length ?? "—"} icon={AlertTriangle} tone="amber" /><ModuleMetric label="Pending requests" value={requests.data?.filter(r => r.status === "pending").length ?? "—"} detail="Within latest 100 requests" icon={ShoppingBag} tone="emerald" /><ModuleMetric label="Purchase orders" value={orders.data?.length ?? "—"} detail="Latest 100 orders" icon={Truck} /></div>
    <WorkflowNotice>Receiving and fulfillment are currently unavailable. Approving a request or issuing an order does not add stock.</WorkflowNotice>
    {access.isLoading ? <ModuleEmpty title="Loading permissions…" /> : !canView ? <ModuleEmpty title="Procurement is unavailable for this account." /> : <>
      <ModuleTabs tabs={[{ id: "stock", label: "Park stock" }, { id: "requests", label: "Stock requests" }, { id: "orders", label: "Purchase orders" }]} value={tab} onChange={setTab} />
      {tab === "stock" && <><div className={cn(moduleCard, "p-4 space-y-3")}><ModuleSearch label="Search stock" placeholder="Search item or park…" value={search} onChange={value => { setSearch(value); setPage(1); }} /><label className="flex items-center gap-2 text-xs font-semibold text-amber-700 dark:text-amber-300"><input type="checkbox" checked={lowOnly} onChange={e => { setLowOnly(e.target.checked); setPage(1); }} />Low stock only</label></div>
        {stocks.isError ? <p role="alert">Stock could not be loaded. <Button onClick={() => stocks.refetch()}>Retry</Button></p> : stocks.isLoading ? <ModuleEmpty title="Loading stock…" /> : !filtered.length ? <ModuleEmpty title="No stock records match." icon={Package} /> : <><div className="grid gap-3 md:grid-cols-2">{filtered.slice((page - 1) * 20, page * 20).map(stock => <article key={stock.id} className={cn(moduleCard, "p-4 space-y-3")}><div className="flex gap-3 items-center"><span className="p-3 rounded-2xl bg-purple-50 dark:bg-white/5 text-[#4B0A8F] dark:text-purple-300"><Package className="size-5" /></span><div className="min-w-0 flex-1"><h2 className="font-black text-sm">{stock.item.name}</h2><p className="text-[11px] text-muted-foreground flex items-center gap-1 mt-1"><MapPin className="size-3" />{stock.park.name}</p></div><span className={cn("rounded-full px-2 py-1 text-[10px] font-bold", stock.quantity < stock.minThreshold ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700")}>{stock.quantity < stock.minThreshold ? "Low stock" : "In stock"}</span></div><div className="flex items-end justify-between border-t border-slate-100 dark:border-white/10 pt-3"><div><p className="text-[10px] uppercase font-bold text-slate-400">Available quantity</p><p className="text-xl font-black mt-1">{stock.quantity} <span className="text-xs font-medium text-muted-foreground">{stock.item.unit}</span></p></div><p className="text-[11px] text-muted-foreground">Minimum {stock.minThreshold}</p></div>{canManage && <Button variant="outline" className="w-full rounded-xl text-xs text-[#4B0A8F] dark:text-purple-300 border-purple-200" onClick={() => { setStockId(stock.id); setRequestOpen(true); }}>Request refill</Button>}</article>)}</div><div className="flex justify-between items-center text-xs"><Button variant="ghost" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Previous</Button><span>Page {page}</span><Button variant="ghost" disabled={page * 20 >= filtered.length} onClick={() => setPage(p => p + 1)}>Next</Button></div></>}
      </>}
      {tab === "requests" && <><h2 className="text-xs font-bold uppercase text-slate-400 tracking-wider px-1">Latest 100 requests</h2>{requests.isError ? <p role="alert">Requests could not be loaded. <Button onClick={() => requests.refetch()}>Retry</Button></p> : requests.isLoading ? <ModuleEmpty title="Loading requests…" /> : !requests.data?.length ? <ModuleEmpty title="No requests in your scope." icon={ShoppingBag} /> : requests.data.map(request => <article key={request.id} className={cn(moduleCard, "p-4 space-y-3")}><div className="flex items-center justify-between gap-2"><h2 className="font-bold text-sm">{request.item.name}</h2><span className="bg-purple-50 dark:bg-white/5 text-purple-700 dark:text-purple-300 rounded-full px-2 py-1 text-[10px] font-bold">{request.status}</span></div><p className="text-xs text-muted-foreground">{request.park.name} · Quantity {request.quantity}</p><p className="text-xs">{request.reason}</p>{canManage && request.status === "pending" && <div className="flex gap-2">{["approved", "rejected"].map(status => <Button key={status} variant="outline" className="rounded-xl text-xs" disabled={mutation.isPending} onClick={() => mutation.mutate({ path: "/api/admin/procurement/requests/" + request.id, method: "PATCH", body: { status } })}>{status === "approved" ? "Approve" : "Reject"}</Button>)}</div>}</article>)}</>}
      {tab === "orders" && <><h2 className="text-xs font-bold uppercase text-slate-400 tracking-wider px-1">Latest 100 purchase orders</h2>{orders.isError ? <p role="alert">Orders could not be loaded. <Button onClick={() => orders.refetch()}>Retry</Button></p> : orders.isLoading ? <ModuleEmpty title="Loading orders…" /> : !orders.data?.length ? <ModuleEmpty title="No orders in your scope." icon={Truck} /> : orders.data.map(order => <article key={order.id} className={cn(moduleCard, "p-4 flex gap-3")}><Truck className="size-5 text-purple-500 mt-1" /><div><h2 className="font-bold text-sm">{order.poNumber}</h2><p className="text-xs mt-1">{order.item.name} · Quantity {order.quantity}</p><p className="text-[11px] text-muted-foreground mt-1">{order.supplierName} · {order.status}</p></div></article>)}</>}
      {canManage && <Sheet open={requestOpen} onOpenChange={open => { if (!mutation.isPending) setRequestOpen(open); }}><SheetContent side={mobile ? "bottom" : "right"} className={cn("overflow-y-auto", mobile && "rounded-t-3xl max-w-[460px] mx-auto max-h-[85dvh]")}><SheetHeader><SheetTitle>Request stock refill</SheetTitle><SheetDescription>Select an item and its park to request replenishment.</SheetDescription></SheetHeader><form className="p-5 space-y-4" onSubmit={event => { event.preventDefault(); if (selected && !mutation.isPending) mutation.mutate({ path: "/api/admin/procurement/requests", method: "POST", body: { parkId: selected.parkId, itemId: selected.itemId, quantity: Number(quantity), reason } }); }}><label className="block text-xs font-bold space-y-1">Item and park<select aria-label="Item and park" className={moduleInput} value={stockId} onChange={event => setStockId(event.target.value)} required><option value="">Select an existing stock item</option>{stocks.data?.map(stock => <option key={stock.id} value={stock.id}>{stock.park.name} — {stock.item.name}</option>)}</select></label><label className="block text-xs font-bold space-y-1">Quantity<Input className="rounded-xl h-11" aria-label="Requested quantity" type="number" min={1} max={1000000} step={1} value={quantity} onChange={event => setQuantity(event.target.value)} required /></label><label className="block text-xs font-bold space-y-1">Reason<Input className="rounded-xl h-11" aria-label="Request reason" minLength={5} maxLength={500} value={reason} onChange={event => setReason(event.target.value)} required /></label><Button className={cn(moduleAction, "w-full h-11")} disabled={!selected || mutation.isPending}>{mutation.isPending ? "Submitting…" : "Submit request"}</Button></form></SheetContent></Sheet>}
    </>}
  </ModuleFrame>;
}
