import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest, NextResponse } from "next/server";

const mocks = vi.hoisted(() => ({ requireRole: vi.fn(), requireCapability: vi.fn(), transaction: vi.fn(), findUnique: vi.fn(), upsert: vi.fn(), deleteOverride: vi.fn(), updateMany: vi.fn(), auditCreate: vi.fn(), createAuditLogData: vi.fn((data) => data), sanitizeAuditReason: vi.fn((value) => value) }));
vi.mock("@/lib/auth/authorize", () => ({ requireRole: mocks.requireRole, requireCapability: mocks.requireCapability }));
vi.mock("@/lib/audit", () => ({ createAuditLogData: mocks.createAuditLogData, sanitizeAuditReason: mocks.sanitizeAuditReason }));
vi.mock("@/lib/db", () => ({ db: { $transaction: mocks.transaction, roleCapabilityOverride: { findMany: vi.fn() } } }));
import { DELETE, PUT } from "./route";
const request = (method: "PUT" | "DELETE", body: Record<string, unknown>) => new NextRequest("http://localhost/api/admin/access/role-overrides", { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

describe("role capability overrides", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.requireRole.mockResolvedValue(null); mocks.requireCapability.mockResolvedValue({ user: { id: "super-admin" } }); mocks.transaction.mockImplementation((work) => work({ roleCapabilityOverride: { findUnique: mocks.findUnique, upsert: mocks.upsert, delete: mocks.deleteOverride }, user: { updateMany: mocks.updateMany }, auditLog: { create: mocks.auditCreate } })); });
  it("rejects non-Super-Admin callers before a mutation", async () => { mocks.requireRole.mockResolvedValue(NextResponse.json({ error: "Forbidden" }, { status: 403 })); const response = await PUT(request("PUT", { role: "park_admin", capability: "attendance.mark", effect: "deny", reason: "Pilot policy" })); expect(response.status).toBe(403); expect(mocks.transaction).not.toHaveBeenCalled(); });
  it("requires role-default administration capability before a mutation", async () => { mocks.requireCapability.mockResolvedValue(NextResponse.json({ error: "Forbidden" }, { status: 403 })); const response = await PUT(request("PUT", { role: "park_admin", capability: "attendance.mark", effect: "deny", reason: "Pilot policy" })); expect(response.status).toBe(403); expect(mocks.requireCapability).toHaveBeenCalledWith("access.role_defaults.manage"); expect(mocks.transaction).not.toHaveBeenCalled(); });
  it("protects Super Admin and access-administration defaults", async () => { const response = await PUT(request("PUT", { role: "program_admin", capability: "access.scope.manage", effect: "allow", reason: "Unsafe" })); expect(response.status).toBe(422); expect(mocks.transaction).not.toHaveBeenCalled(); });
  it("updates a role exception and invalidates active accounts of that role", async () => { mocks.findUnique.mockResolvedValue(null); mocks.upsert.mockResolvedValue({ id: "role-override-1", role: "park_admin", capability: "attendance.mark", effect: "deny", reason: "Pilot policy", updatedAt: new Date() }); const response = await PUT(request("PUT", { role: "park_admin", capability: "attendance.mark", effect: "deny", reason: "Pilot policy" })); expect(response.status).toBe(200); expect(mocks.updateMany).toHaveBeenCalledWith({ where: { isActive: true, staffMeta: { is: { role: "park_admin" } } }, data: { tokenVersion: { increment: 1 } } }); expect(mocks.auditCreate).toHaveBeenCalledTimes(1); });
  it("reverts an existing exception in the same transaction", async () => { mocks.findUnique.mockResolvedValue({ id: "role-override-1", effect: "deny" }); const response = await DELETE(request("DELETE", { role: "park_admin", capability: "attendance.mark", reason: "Restored default" })); expect(response.status).toBe(200); expect(mocks.deleteOverride).toHaveBeenCalledWith({ where: { id: "role-override-1" } }); expect(mocks.updateMany).toHaveBeenCalledTimes(1); expect(mocks.auditCreate).toHaveBeenCalledTimes(1); });
});
