-- Additive migration: StudentExtendedProfile model
-- Created on-demand for supplementary biographical, developmental, and wellbeing data.

CREATE TABLE "student_extended_profiles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "participantId" TEXT NOT NULL,
    "school" TEXT,
    "college" TEXT,
    "educationSystem" TEXT,
    "previousResults" TEXT,
    "awardsAchievements" TEXT,
    "averageGrade" TEXT,
    "favouriteSubjects" TEXT,
    "fatherName" TEXT,
    "fatherOccupation" TEXT,
    "siblings" TEXT,
    "financialStatus" TEXT,
    "nativeArea" TEXT,
    "ethnicity" TEXT,
    "modeOfTransport" TEXT,
    "subjectsOfInterest" TEXT,
    "extraCurricular" TEXT,
    "hobbies" TEXT,
    "sports" TEXT,
    "learningStyle" TEXT,
    "curiosity" TEXT,
    "specialTalent" TEXT,
    "currentSkills" TEXT,
    "skillsWantToLearn" TEXT,
    "generalGoals" TEXT,
    "vision" TEXT,
    "mission" TEXT,
    "deenBackground" TEXT,
    "careerAspirations" TEXT,
    "academicInterests" TEXT,
    "collegePlans" TEXT,
    "futureCareerGoals" TEXT,
    "strengths" TEXT,
    "weaknesses" TEXT,
    "goodHabits" TEXT,
    "badHabits" TEXT,
    "disability" TEXT,
    "specialNeed" TEXT,
    "moralCharacter" TEXT,
    "namaz" TEXT,
    "leadershipSkills" TEXT,
    "personalityResponsibility" TEXT,
    "communicationSkills" TEXT,
    "teamworkSkills" TEXT,
    "problemSolvingSkills" TEXT,
    "creativity" TEXT,
    "criticalThinking" TEXT,
    "adaptability" TEXT,
    "initiative" TEXT,
    "selfMotivation" TEXT,
    "integrity" TEXT,
    "empathy" TEXT,
    "reading" TEXT,
    "learningInterest" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "student_extended_profiles_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "participants" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "student_extended_profiles_participantId_key" ON "student_extended_profiles"("participantId");
CREATE INDEX "student_extended_profiles_participantId_idx" ON "student_extended_profiles"("participantId");
